disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "FGC Ireland"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "fgcireland-fist.png"
description = "Home of the Fighting Game Community in Ireland. Run the set!"

["params.author"]
name = "Paul O'Shea"
