backend:
  name: github
  branch: main  # or master, depending on your default branch
  repo: D4RKONION/fgcireland.com # Replace with your actual repo
  base_url: https://auth.fgcireland.com
  squash_merges: true
  
  # GitHub App authentication
  app_id: "1636334"  # Replace with your App ID
  installation_id: "76740093"  # Replace with your Installation ID
  
  # Enable editorial workflow for content review
  cms_label_prefix: "decap-cms/"

# Enable editorial workflow (creates PRs instead of direct commits)
publish_mode: editorial_workflow

# Media files configuration
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Collections define the structure of your content
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    path: "{{slug}}/index"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false  # Disable preview pane for better performance
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - label: "Author"
        name: "authors"
        widget: "select"
        multiple: true
        options:
          - {label: "D4RK ONION", value: "d4rk-onion"}
          - {label: "SHIN-A", value: "shin-a"}

      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 1024000 # in bytes

      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Summary/Lead line (Shown in links & at top of article)", name: "description", widget: "text", required: true}
      - {label: "Body", name: "body", widget: "markdown"}